# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design6.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1749, 767)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.Titre1 = QtWidgets.QLabel(self.splitter_3)
        self.Titre1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Titre1.setObjectName("Titre1")
        self.label_1 = QtWidgets.QLabel(self.splitter_3)
        self.label_1.setEnabled(True)
        self.label_1.setObjectName("label_1")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter_3)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_9 = QtWidgets.QTableWidget(self.splitter_3)
        self.tableWidget_9.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_9.setMaximumSize(QtCore.QSize(16777215, 131))
        self.tableWidget_9.setObjectName("tableWidget_9")
        self.tableWidget_9.setColumnCount(0)
        self.tableWidget_9.setRowCount(0)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.Titre2 = QtWidgets.QLabel(self.splitter_2)
        self.Titre2.setMinimumSize(QtCore.QSize(0, 27))
        self.Titre2.setObjectName("Titre2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.splitter_2)
        self.tableWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.Titre3 = QtWidgets.QLabel(self.splitter_2)
        self.Titre3.setObjectName("Titre3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.splitter_2)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tableWidget_10 = QtWidgets.QTableWidget(self.splitter_2)
        self.tableWidget_10.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_10.setMaximumSize(QtCore.QSize(16777215, 131))
        self.tableWidget_10.setObjectName("tableWidget_10")
        self.tableWidget_10.setColumnCount(0)
        self.tableWidget_10.setRowCount(0)
        self.splitter = QtWidgets.QSplitter(self.splitter_5)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.Titre4 = QtWidgets.QLabel(self.splitter)
        self.Titre4.setMinimumSize(QtCore.QSize(0, 27))
        self.Titre4.setObjectName("Titre4")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.Titre5 = QtWidgets.QLabel(self.splitter)
        self.Titre5.setObjectName("Titre5")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.tableWidget_11 = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_11.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_11.setMaximumSize(QtCore.QSize(16777215, 131))
        self.tableWidget_11.setObjectName("tableWidget_11")
        self.tableWidget_11.setColumnCount(0)
        self.tableWidget_11.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.splitter_5)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Titre6 = QtWidgets.QLabel(self.widget)
        self.Titre6.setObjectName("Titre6")
        self.verticalLayout_2.addWidget(self.Titre6)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_6.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(0)
        self.tableWidget_6.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_6)
        self.widget1 = QtWidgets.QWidget(self.splitter_5)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Titre7 = QtWidgets.QLabel(self.widget1)
        self.Titre7.setMaximumSize(QtCore.QSize(280, 16777215))
        self.Titre7.setObjectName("Titre7")
        self.verticalLayout.addWidget(self.Titre7)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.widget1)
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(0)
        self.tableWidget_7.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_7)
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.Titre8 = QtWidgets.QLabel(self.splitter_4)
        self.Titre8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Titre8.setObjectName("Titre8")
        self.tableWidget_8 = QtWidgets.QTableWidget(self.splitter_4)
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(0)
        self.tableWidget_8.setRowCount(0)
        self.gridLayout.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout.addWidget(self.btnBrowse)
        self.btnActualize = QtWidgets.QPushButton(self.centralwidget)
        self.btnActualize.setObjectName("btnActualize")
        self.horizontalLayout.addWidget(self.btnActualize)
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnQuit = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout.addWidget(self.btnQuit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1749, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titre1.setText(_translate("MainWindow", "Label 1"))
        self.label_1.setText(_translate("MainWindow", "TextLabel1"))
        self.Titre2.setText(_translate("MainWindow", "Label 2"))
        self.label_2.setText(_translate("MainWindow", "TextLabel2"))
        self.Titre3.setText(_translate("MainWindow", "Label 3"))
        self.Titre4.setText(_translate("MainWindow", "Label 4"))
        self.label_3.setText(_translate("MainWindow", "TextLabel3"))
        self.Titre5.setText(_translate("MainWindow", "Label 5"))
        self.Titre6.setText(_translate("MainWindow", "Label 6"))
        self.label_4.setText(_translate("MainWindow", "TextLabel4"))
        self.Titre7.setText(_translate("MainWindow", "Label 7"))
        self.Titre8.setText(_translate("MainWindow", "Label 8"))
        self.btnBrowse.setText(_translate("MainWindow", "Pick a Folder"))
        self.btnActualize.setText(_translate("MainWindow", "Actualize"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

